---
- name: Asenna nano tekstieditori
  hosts: all
  become: true

  tasks:
    - name: Asenna nano
      apt:
        name: nano
        state: present
        update_cache: yes

    - name: Tarkista onko nano jo asennettu
      shell: which nano
      register: nano_path
      ignore_errors: yes

    - name: Vahvista että nano on asennettu
      debug:
        msg: "Nano on asennettu onnistuneesti"
      when: nano_path.rc == 0
