---
- name: Testaa Unifi-laitteen tila
  hosts: 172.30.133.134
  gather_facts: false
  tasks:
    - name: Aja mca-status
      raw: mca-status
      register: status_output

    - name: Tulosta laitteen tila
      debug:
        msg: "{{ status_output.stdout_lines }}"
