- name: Unifi-laitteen WLAN-tarkistus
  hosts: unifi
  gather_facts: no
  vars:
    config_path: /tmp/system.cfg
  tasks:

    - name: N채yt채 WLAN-konfiguraatio (system.cfg)
      raw: cat {{ config_path }} | grep -i wifi
      register: wifi_config

    - name: Tulosta WLAN-konfiguraatio
      debug:
        msg: "{{ wifi_config.stdout_lines }}"

    - name: N채yt채 laitteen tila (mca-status)
      raw: mca-status
      register: mca_info

    - name: Tulosta laitteen tila
      debug:
        msg: "{{ mca_info.stdout_lines }}"
