- name: Testaa Unifi-laite: show info
  hosts: 172.30.133.134
  gather_facts: no
  tasks:
    - name: Aja show info
      raw: show info
      register: show_info_output

    - name: Tulosta show info -tulokset
      debug:
        msg: "{{ show_info_output.stdout_lines }}"
