---
- name: Unifi-kytkimen perustiedot
  hosts: 10.1.0.60
  gather_facts: false
  tasks:

    - name: Lue laitetiedot (board.info)
      raw: cat /etc/board.info
      register: board_info

    - name: Tulosta laitetiedot
      debug:
        msg: "{{ board_info.stdout_lines }}"

    - name: Lue ohjelmistoversio
      raw: cat /etc/version
      register: version_info

    - name: Tulosta versiotiedot
      debug:
        msg: "{{ version_info.stdout_lines }}"
