---
- name: Näytä Unifi-kytkimen info
  hosts: 172.30.133.134
  gather_facts: no
  tasks:
    - name: Aja info-komento
      raw: info
      register: info_output

    - name: Tulosta info-tuloste
      debug:
        msg: "{{ info_output.stdout_lines }}"
