- name: Testaa Unifi show info
  hosts: 172.30.133.134
  gather_facts: false
  tasks:
    - name: Aja show info
      raw: show info
      register: show_output

    - name: Tulosta tulos
      debug:
        msg: "{{ show_output.stdout_lines }}"
